config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :farms, except: :desroy

  root 'farms#index'
end

app/models/farm.rb
class Farm < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :user, validate: true

  validates :name, :image, :address, :zip_code, :place, presence: true
  validates :name, uniqueness: true

  has_many :products
  accepts_nested_attributes_for :products, reject_if: :all_blank, allow_destroy: true

  geocoded_by :full_street_address
  after_validation :geocode

  def full_street_address
    "#{address}, #{zip_code} #{place}, Schweiz"
  end

  scope :has_latitude_and_longitude, -> { where.not(latitude: nil, longitude: nil) }
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :farm, validate: true

  validates :name, presence: true
  validates :name, uniqueness: { scope: :farm_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :farm
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    if user.farm.present?
      farm_path user.farm
    else
      new_farm_path
    end
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_farm, only: [:show, :edit, :update, :destroy]

  def index
    @farms = Farm.all

    respond_to do |format|
      format.html
      format.json { render json: @farms.has_latitude_and_longitude }
    end
  end

  def show
  end

  def new
    if current_user.farm.present?
      render :edit
    else
      @farm = Farm.new
    end
  end

  def edit
  end

  def create
    @farm = Farm.new(farm_params)

    respond_to do |format|
      if @farm.save
        format.html { redirect_to @farm, notice: 'Farm was successfully created.' }
        format.json { render :show, status: :created, location: @farm }
      else
        format.html { render :new }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @farm.update(farm_params)
        format.html { redirect_to @farm, notice: 'Farm was successfully updated.' }
        format.json { render :show, status: :ok, location: @farm }
      else
        format.html { render :edit }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_farm
    @farm = Farm.find(params[:id])
  end

  def farm_params
    params.require(:farm).permit(
      :name, :address, :zip_code, :place, :image,
      products_attributes: [:id, :name, :_destroy]
    ).merge!(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_css_class(alert)
    if alert == 'alert'
      'alert-danger'
    else
      'alert-info'
    end
  end

  def google_maps_image(latitude, longitude)
    "https://maps.googleapis.com/maps/api/staticmap?size=300x150&zoom=13&scale=2&markers=#{latitude},#{longitude}"
  end
end

app/views/application/_head.haml
%head
  %meta{ charset: 'utf-8' }
  %meta{ content: 'IE=edge', 'http-equiv' => 'X-UA-Compatible' }
  %meta{ content: 'width=device-width, initial-scale=1', name: 'viewport' }

  %title Saison Produkte | Finde deine Saisonprodukte beim Bauern nebenan

  %link{:href => "https://fonts.googleapis.com/css?family=Indie+Flower", :rel => "stylesheet", :type => "text/css"}/
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  %script{:src => "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_MAPS_API_KEY']}", :type => "text/javascript"}

  /[if lt IE 9]
    <script src='https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'></script>
    <script src='https://oss.maxcdn.com/respond/1.4.2/respond.min.js'></script>

app/views/application/_navigation.haml
%nav.navbar{ class: "#{ 'navbar-default' if current_user.present? }" }
  .container-fluid
    .navbar-header
      = link_to root_path, class: 'navbar-brand' do
        %span.brand-saison= t '.season'
        %span.brand-produkte= t '.products'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if current_user.present?
          - if current_user.farm.present? && current_user.farm.persisted?
            %li
              = link_to t_action(:edit), edit_farm_path(current_user.farm)
          %li
            = link_to t_action(:sign_out), destroy_user_session_path, :method => :delete
        - else
          %li
            = link_to t_action(:register), new_user_registration_path
          %li
            = link_to t_action(:sign_in), new_user_session_path

app/views/application/_notifications.haml
.alert.alert-dismissible.fade.in{ role: 'alert', class: alert_css_class(flash.keys.first) }
  %button.close{ aria: { label: 'Close' }, data: { dismiss: 'alert' }, type: 'button' }
    %span{ aria: { hidden: 'true' } } ×
  %p
    = alert || notice

app/views/farms/_form.html.haml
= simple_form_for @farm, html: { multipart: true } do |f|
  - if f.error_notification.present?
    .row
      .col-md-12
        = f.error_notification
  .row
    .col-md-12
      = f.input :image, as: :image_preview
    .col-md-12
      = f.input :name
    .col-md-12
      = f.input :address
    .col-md-4.col-sm-4.col-xs-4
      = f.input :zip_code
    .col-md-8.col-sm-8.col-xs-8
      = f.input :place
  .row
    .col-md-12
      %h3= t_attr(:products)
  #products
    = f.simple_fields_for :products do |product|
      = render 'product_fields', f: product
  .row
    .col-md-12
      .links
        = link_to_add_association t_action('.add_product'), f, :products, class: 'btn btn-success'
  .row
    .col-md-12
      = f.button :submit

app/views/farms/_product_fields.haml
.row
  .nested-fields
    .col-md-10.col-sm-8.col-xs-8
      = f.input :name
    .col-md-2.col-sm-4.col-xs-4
      = f.input :_destroy, as: :boolean

app/views/farms/edit.html.haml
.container
  .row
    .col-md-offset-3.col-md-6
      %h1= t_title

      = render 'form'

app/views/farms/index.html.haml
.container
  .row
    .col-md-12
      %h3 Saisonprodukte zeigt dir, welche Höfe in deiner Nähe sind und was diese Höfe momentan verkaufen.
      %p
        %strong Bist du Landwirt?
        Registriere dich auf unserer Webseite und zeig deinen Kunden, welche Produkte gerade aktuell sind.
        %br
        Dein Vorteil – eine gratis Webseite, welche immer auf dem neusten technologischen Stand ist- eine Möglichkeit auf einfache Art und Weise von deinen Kunden gefunden zu werden –
        Ein erster Schritt, ohne Direktzahlungen auszukommen. Unabhängigkeit kann so schön sein

#map

.container
  .row
    %table.table
      %thead
        %tr
          %th= t_attr :name
          %th= t_attr :address
          %th= t_attr :place
          %th= t_attr :products

      %tbody
        - @farms.each do |farm|
          %tr
            %td= link_to farm.name, farm_path(farm)
            %td= farm.address
            %td
              = farm.zip_code
              = farm.place
            %td
              = farm.products.map(&:name).join(', ')

:javascript
  $( document ).ready(function() {
    initMap()
  })

app/views/farms/new.html.haml
.container
  .row
    .col-md-offset-3.col-md-6
      %h1= t_title

      = render 'form'

app/views/farms/show.html.haml
- content_for :farm_image do
  farm-image

- content_for :background_image do
  = "background-image: url(#{@farm.image_url})"
  
.plate-wrapper
  .text-center
    .plate
      %h3= t('.welcome')
    .plate
      %h1
        = @farm.name
      %h4
        = @farm.address
      %h4
        = @farm.zip_code
        = @farm.place
    - if @farm.latitude.present? && @farm.longitude.present?
      .plate
        = link_to "https://maps.google.com/?q=#{@farm.full_street_address}", target: '_blank' do
          = image_tag google_maps_image(@farm.latitude, @farm.longitude), class: 'img-responsive'

    - if @farm.products.exists?
      .plate
        %h3= t '.products'
      - @farm.products.each do |product|
        .plate
          %h3
            %strong
              = product.name

app/views/layouts/application.haml
!!!
%html{ lang: 'de'}
  = render 'head'
  %body{ class: yield(:farm_image), style: yield(:background_image) }
    = render 'navigation'
    .container
      = render 'notifications' if flash.present?
    = yield